version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./modules:/app/modules
      - ./utils:/app/utils
    env_file:
      - ./config/.env
    ports:
      - "3000:3000"  # Adjust the port as necessary
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  data: {}