services:
  node-app:
    build: 
      context: .
      dockerfile: infrastructure/node/dev/Dockerfile
    restart: on-failure
    volumes:
      - ./src:/app
      - /app/node_modules # Avoids overwriting node_modules in the container
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    networks:
      - tlbot_network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tlbot.rule=Host(`tl-bot.mikorh.com`)"
      - "traefik.http.routers.tlbot.entrypoints=websecure"
      - "traefik.http.routers.tlbot.tls.certresolver=letsencrypt"
      - "traefik.http.services.tlbot.loadbalancer.server.port=${PORT}"

  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${PASS_ROOT_DB}
      MARIADB_DATABASE: ${TLBOT_DB}
      MARIADB_USER: ${USER_DB}
      MARIADB_PASSWORD: ${PASS_DB}
    ports:
      - "${PORT_DB}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./infrastructure/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-sql.sql
    env_file:
      - ./.env
    networks:
      - tlbot_network

    healthcheck:
      test: ["CMD", "mariadb", "-h", "localhost", "-u$USER_DB", "-p$PASS_DB","-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


volumes:
  db_data:

networks:
  tlbot_network:
    driver: bridge
  traefik:
    external: true