# Usa una imagen oficial de Node.js como base
FROM node:20-alpine

# Instala curl para el healthcheck
RUN apk add --no-cache curl

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY /src/ .
# COPY /src/package*.json ./

# Instala las dependencias
RUN npm install

# Comando para iniciar el bot
CMD ["npm", "start"]