# Usa una imagen oficial de Node.js como base
FROM node:20-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY /src/ .
# COPY /src/package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
# COPY /src/ .

# Expone el puerto si tu bot lo necesita (opcional)
# EXPOSE 3000

# Comando para iniciar el bot
CMD ["node", "bot-dev.js"]