name: Deploy to Server

on:
  push:
    branches:
      - main # Cambia "main" por la rama que quieras monitorear

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/admin_MKL/telegram-bot   # Cambia esta ruta por la ruta de tu proyecto en el servidor
          git pull origin main              # Cambia "main" si usas otra rama
          pm2 restart all                   # Reinicia PM2